# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '14'
- script: npm install
- task: GoTool@0
  inputs:
    version: '1.16.0'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
# - task: Go@0
#   inputs:
#     command: 'build'
#     workingDirectory: '$(System.DefaultWorkingDirectory)'
# - task: CopyFiles@2
#   inputs:
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#      artifactName: drop
# - name: Build sources
#       run: |
#         TAGS="bindata" make build
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
