trigger:
- master

pool: Default

steps:
- task: NodeTool@0 
  condition: succeeded()
  inputs:
    versionSpec: '14'
- script: npm install
  condition: succeeded()
- task: GoTool@0
  condition: succeeded()
  inputs:
    version: '1.16.3'
- task: Go@0
  condition: succeeded()
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: TAGS="bindata" make build
  condition: succeeded()
- script: 'echo "$(Build.DefinitionName), $(Build.BuildID), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)' # Required 
    artifactName: 'gitea' # Optional
    artifactType: 'pipeline' # Required. Options: pipeline, filepath. Default value: pipeline
    fileSharePath: '\server\folderName' # Required when artifactType = filepath
    #parallel: false # Optional. Default value: false
    #parallelCount: 1 # Optional. Value must be at least 1 and not greater than 128. Default value: 8  
#   inputs:
#     command: 'build'
#     workingDirectory: '$(System.DefaultWorkingDirectory)'
# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(Build.SourcesDirectory)'
#     contents: 'gitea'
#     targetFolder: '$(Build.ArtifactStagingDirectory)'
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifact: gitea'
#   inputs:
#      command: 'pbulish'
#      projects: './gitea'
#      publishWebProjects: false
#      zipAfterPublish: true
#   condition: succeeded()
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish artifact: gitea'
#   inputs:
#      artifactName: gitea
#   condition: succeeded()
# - name: Build sources
#       run: |
#         TAGS="bindata" make build
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
