trigger:
- master

pool: Default

steps:
- task: NodeTool@0 
  condition: succeeded()
  inputs:
    versionSpec: '14'
- script: npm install
  condition: succeeded()
- task: GoTool@0
  condition: succeeded()
  inputs:
    version: '1.16.3'
- task: Go@0
  condition: succeeded()
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- script: TAGS="bindata" make build
  condition: succeeded()
# - task: Go@0
#   inputs:
#     command: 'build'
#     workingDirectory: '$(System.DefaultWorkingDirectory)'
# - task: CopyFiles@2
#   inputs:
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
# - task: PublishBuildArtifacts@1
#   inputs:
#      artifactName: drop
# - name: Build sources
#       run: |
#         TAGS="bindata" make build
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
