version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"    
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      nodejs: 14
      golang: 1.15
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - make -v 
      - node -v
      - npm install -g npm     
      - pwd
      # - command
  build:
    commands:
      - TAGS="bindata" make build
      - pwd
      - cd gitea
      - ls -la
      - mv gitea application
      - chmod 777 application 
      - zip application.zip application go.mod Procfile
      - ls -la
      # - command
  #post_build:
  #  commands:
  #    - mv build-output/**/* ./
  #    - mv build-output/* ./
  #    - rm -R build-output
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
      - './gitea/application.zip'
    # - location
#  name: gitea-$(date +%Y-%m-%d)
#  discard-paths: yes
#  base-directory: public
#cache:
  #paths:
    # - paths
